language: bash

services:
 - docker

git:
 submodules: false

jobs:
 include:
  - stage: Base
    name: Verificarlo
    env: DFILE=base/Dockerfile.ubuntu14.04-verificarlo  DIMAGE=ubuntu14.04-base
  - stage: Environments (Level 1)
    name: Blas & Lapack
    env: DFILE=level1/Dockerfile.ubuntu14.04-blas-lapack  DIMAGE=ubuntu14.04-blas-lapack
  - name: Python
    env: DFILE=level1/Dockerfile.ubuntu14.04-python       DIMAGE=ubuntu14.04-python
  - name: Libmath
    env: DFILE=level1/Dockerfile.libmath DIMAGE=ubuntu14.04-libmath
  - stage: Environments (Level 2)
    name: Python & Numpy
    env: DFILE=level2/Dockerfile.ubuntu14.04-python-numpy DIMAGE=ubuntu14.04-python-numpy
  - stage: Applications
    name: FSL
    env: DFILE=apps/fsl/Dockerfile.libmath.fsl DIMAGE=ubuntu14.04-libmath-fsl
  - name: AFNI
    env: DFILE=apps/afni/Dockerfile.libmath.afni DIMAGE=ubuntu14.04-libmath-afni


script:
 - ./fuzzy/build/login.sh 
 - ./fuzzy/build/build.sh ${DFILE} ${DIMAGE}
 # - travis_wait 30 ./fuzzy/build/build.sh ${DFILE} ${DIMAGE}
 
# Publish early stages always, only publish applications when we have a new tag (temporary)
# - if [ "$TRAVIS_TAG" != "" ] || [ "$TRAVIS_BUILD_STAGE_NAME" != "App" ]; then ./fuzzy/build/push.sh ${DIMAGE}; fi

# Publish always after success
after_script:
  - ./fuzzy/build/push.sh ${DIMAGE}
